// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaAPI.Models;

#nullable disable

namespace VeterinariaAPI.Migrations
{
    [DbContext(typeof(VeterinariodbContext))]
    [Migration("20260904061906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Citas__3214EC07A639186A");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clientes__3214EC070C5DA8E9");

                    b.HasIndex(new[] { "DocumentoIdentidad" }, "UQ__Clientes__049E81A92BDD82D2")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC07AF440D4C");

                    b.HasIndex("CitaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetallesFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int?>("InsumoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Detalles__3214EC073EE87D18");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("InsumoId");

                    b.ToTable("DetallesFactura", (string)null);
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetallesRecetum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Detalles__3214EC074095EE85");

                    b.HasIndex("InsumoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("DetallesReceta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoBase")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Especial__3214EC0723BFF743");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))", "DF_Facturas_FechaEmision");

                    b.Property<decimal>("MontoImpuestos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Facturas__3214EC07EDC3F268");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Insumos__3214EC0728749262");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Paciente__3214EC076582479F");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidaHasta")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Recetas__3214EC07247EC520");

                    b.HasIndex(new[] { "ConsultaId" }, "UQ__Recetas__7D0B7DCDF5A12854")
                        .IsUnique();

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PermisosEscritura")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07445D2FB3");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC0795B09A7E");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534A20CB241")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Especialidade", "Especialidad")
                        .WithMany("Cita")
                        .HasForeignKey("EspecialidadId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Especialidades");

                    b.HasOne("VeterinariaAPI.Models.Paciente", "Paciente")
                        .WithMany("Cita")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Pacientes");

                    b.HasOne("VeterinariaAPI.Models.Usuario", "Usuario")
                        .WithMany("Cita")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Usuarios");

                    b.Navigation("Especialidad");

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Consulta", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Cita", "Cita")
                        .WithMany("Consulta")
                        .HasForeignKey("CitaId")
                        .HasConstraintName("FK_Consultas_Citas");

                    b.HasOne("VeterinariaAPI.Models.Paciente", "Paciente")
                        .WithMany("Consulta")
                        .HasForeignKey("PacienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Consultas_Pacientes");

                    b.Navigation("Cita");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetallesFactura", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Consulta", "Consulta")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("ConsultaId")
                        .HasConstraintName("FK_DetallesFactura_Consultas");

                    b.HasOne("VeterinariaAPI.Models.Factura", "Factura")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("FacturaId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesFactura_Facturas");

                    b.HasOne("VeterinariaAPI.Models.Insumo", "Insumo")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("InsumoId")
                        .HasConstraintName("FK_DetallesFactura_Insumos");

                    b.Navigation("Consulta");

                    b.Navigation("Factura");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetallesRecetum", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Insumo", "Insumo")
                        .WithMany("DetallesReceta")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesReceta_Insumos");

                    b.HasOne("VeterinariaAPI.Models.Receta", "Receta")
                        .WithMany("DetallesReceta")
                        .HasForeignKey("RecetaId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesReceta_Recetas");

                    b.Navigation("Insumo");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Factura", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Clientes");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Paciente", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Cliente", "Cliente")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClienteId")
                        .IsRequired()
                        .HasConstraintName("FK_Pacientes_Clientes");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Receta", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Consulta", "Consulta")
                        .WithOne("Receta")
                        .HasForeignKey("VeterinariaAPI.Models.Receta", "ConsultaId")
                        .IsRequired()
                        .HasConstraintName("FK_Recetas_Consultas");

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Usuario", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Consulta", b =>
                {
                    b.Navigation("DetallesFacturas");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Especialidade", b =>
                {
                    b.Navigation("Cita");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Factura", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Insumo", b =>
                {
                    b.Navigation("DetallesFacturas");

                    b.Navigation("DetallesReceta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Paciente", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Receta", b =>
                {
                    b.Navigation("DetallesReceta");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Usuario", b =>
                {
                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
